# กำหนด NetWork ให้กับ Container
networks:
  goapi_network:
    name: goapi_network
    driver: bridge

services:
  # Postgres Database
  pgdb:
    image: postgres:15.8
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: appointment
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    networks:
      - goapi_network
  # Go API
  goapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_sample_api
    ports:
      - "8080:8000"
    environment:
      - DB_HOST=pgdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_NAME=appointment
      - DB_TIMEZONE=Asia/Bangkok
      - DB_SSLMODE=disable
    depends_on:
      - pgdb
    restart: always
    networks:
      - goapi_network
volumes:
  postgresdb: